server:
    port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marouanedbibih/micromall-config
          default-label: main

---
logging:
  level:
    root: INFO
    